### ISSUE TITLE
Update to new version on Angular

### ISSUE THREAD

**Issue by igormusic** [Tarnn/CarApp#1]
BTW - how do you run the app? ng serve?

**Comment by Tarnn** [comment]
Hey,

Node sever within the path server.js is located. Ive been working on this
with mongo, node, express and angular. So you must npm install the
dependencies from the express path and then again from thr client path.

**Comment by Tarnn** [comment]
Npm install at carApp/
Npm install at carApp/client
Then: node server at carApp/
Localhost:3000 on the browser

Some components might be commented out as i am going to create routerlinks for each page essentially. Can explain more in detail what I am doing with this project.
